enable-module-update = true
parallel-jobs = 1
compression-level = 9
include-stock = "split"
riplib = true
cli-version = "dev"


[YouTube-Morphe]
app-name = "YouTube"
brand = "Morphe"
build-mode = "both"
excluded-patches = "'Custom branding'"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
version = "latest"

[YouTube-Music-Morphe]
app-name = "YouTube Music"
brand = "Morphe"
build-mode = "both"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
version = "latest"

[Reddit-Morphe]
app-name = "Reddit"
brand = "Morphe"
build-mode = "both"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit/"
version = "latest"

[X-Piko]
app-name = "X"
brand = "Piko"
pkg-name = "com.twitter.android"
build-mode = "apk"
uptodown-dlurl = "https://twitter.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/x-corp/twitter"
version = "latest"
patches-source = "crimera/piko-newx"
patches-version = "dev"
included-patches = "'NewX: Restore Twitter branding'"

[Instagram-Piko]
app-name = "Instagram"
brand = "Piko"
pkg-name = "com.instagram.android"
build-mode = "apk"
uptodown-dlurl = "https://instagram.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/instagram/instagram-instagram"
direct-dlurl = "https://github.com/krvstek/uni-storage/releases/download/instagram/com.instagram.android-439.0.0.37.89-arm64-v8a.apkm"
version = "439.0.0.37.89"
patches-source = "crimera/piko"
patches-version = "dev"